version: "3.7"

services:
  web:
    image: acdemeg/web-downloader-frontend:1.0.0
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    ports:
      - "8002:80"
      