name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 16.x
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Yarn install
        uses: Borales/actions-yarn@v5.0.0
        with:
          cmd: install

      - name: Yarn build
        uses: Borales/actions-yarn@v5.0.0
        with:
          cmd: build
